name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npx pnpm install
    - name: Build
      run: |
        cd blog
        ./scripts build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.4.7
      with:
        BRANCH: gh-pages
        FOLDER: out
