name: CI

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:

    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npx pnpm i
    - name: Build
      run: |
        cd blog
        ./scripts.js build
    - name: Deploy to github.io
      uses: peaceiris/actions-gh-pages@v3.5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: blog/out
